title: tch4vi
description: Cybersecurity, Pentesting writeups & learning notes
theme: null
url: "https://tch4vi.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge          # enlaza kramdown con rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false            # ponlo en true si quieres números de línea

collections:
  writeups:
    output: true
    permalink: /writeups/:name/
  articles:
    output: true
    permalink: /articles/:name/

timezone: Europe/Madrid              # fechas correctas en tus posts

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: writeup                # aplica el layout writeup a todos automáticamente
